// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {instance} from '../models';

export function Attach():Promise<main.Resp>;

export function Avatar(arg1:string):Promise<string>;

export function Close():Promise<void>;

export function Execute(arg1:string):Promise<main.Resp>;

export function FullScreen():Promise<void>;

export function Get():Promise<instance.RobloxInstances>;

export function GetScriptsItems():Promise<{[key: string]: string}>;

export function IsInjected():Promise<boolean>;

export function KillRoblox():Promise<main.Resp>;

export function Minimize():Promise<void>;

export function ReturnClients():Promise<Array<instance.RobloxInstances>>;

export function Savefrontend(arg1:string,arg2:string):Promise<void>;

export function SetClient(arg1:number):Promise<void>;

export function Version():Promise<string>;
