// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Attach() {
  return window['go']['main']['App']['Attach']();
}

export function Avatar(arg1) {
  return window['go']['main']['App']['Avatar'](arg1);
}

export function Close() {
  return window['go']['main']['App']['Close']();
}

export function Execute(arg1) {
  return window['go']['main']['App']['Execute'](arg1);
}

export function FullScreen() {
  return window['go']['main']['App']['FullScreen']();
}

export function Get() {
  return window['go']['main']['App']['Get']();
}

export function GetScriptsItems() {
  return window['go']['main']['App']['GetScriptsItems']();
}

export function IsInjected() {
  return window['go']['main']['App']['IsInjected']();
}

export function KillRoblox() {
  return window['go']['main']['App']['KillRoblox']();
}

export function Minimize() {
  return window['go']['main']['App']['Minimize']();
}

export function ReturnClients() {
  return window['go']['main']['App']['ReturnClients']();
}

export function Savefrontend(arg1, arg2) {
  return window['go']['main']['App']['Savefrontend'](arg1, arg2);
}

export function SetClient(arg1) {
  return window['go']['main']['App']['SetClient'](arg1);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}
